name: integrate
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt -- --check
      - name: Build
        run: cargo build
      - name: Test (No features)
        run: cargo test --no-default-features
      - name: Test (All features)
        run: cargo test --all-features
      - name: Check clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

